- name: remove calico default pool
  shell: calicoctl pool remove 192.168.0.0/16
  environment: 
    ETCD_AUTHORITY: 127.0.0.1:{{ etcd_client_port }}
  changed_when: False
  ignore_errors: yes

- name: check if lain pool exists
  shell: calicoctl pool show --ipv4 | grep "{{ calico_default_network }}" 
  environment: 
    ETCD_AUTHORITY: 127.0.0.1:{{ etcd_client_port }}
  register: result
  changed_when: False
  ignore_errors: yes

- name: add lain pool
  shell: calicoctl pool add {{ calico_default_network }} --nat-outgoing
  environment: 
    ETCD_AUTHORITY: 127.0.0.1:{{ etcd_client_port }}
  when: result|failed and not calico_ipip|bool

- name: add lain pool with ipip
  shell: calicoctl pool add {{ calico_default_network }} --nat-outgoing --ipip
  environment: 
    ETCD_AUTHORITY: 127.0.0.1:{{ etcd_client_port }}
  when: result|failed and calico_ipip|bool

- name: check if lain network exists
  shell: docker network ls | grep " lain "
  register: result
  changed_when: False
  ignore_errors: yes

- name: add lain network
  shell: docker network create --driver calico --ipam-driver calico --subnet={{ calico_default_network }} lain
  when: result|failed

- name: check if some network exist
  shell: docker network ls | grep {{ item }}
  with_items:
    - "registry"
  register: result
  changed_when: False
  ignore_errors: yes

- name: create layer1 network
  shell: docker network create --driver calico --ipam-driver calico --subnet={{ calico_default_network }} {{ item }}
  with_items:
    - "tinydns"
    - "console"
    - "webrouter"
    - "registry"
    - "backupctl"
    - "lvault"
  when: result|failed

- name: add profile rules allow from lain
  shell: calicoctl profile {{ item }} rule add inbound --at=1 allow from tag lain
  environment:
    ETCD_AUTHORITY: 127.0.0.1:{{ etcd_client_port }}
  with_items:
    - "tinydns"
    - "console"
    - "backupctl"
    - "webrouter"
    - "registry"
    - "lvault"
  when: result|failed

- name: add tinydns rules allow to udp 53
  command: calicoctl profile tinydns rule add inbound --at=1 allow udp to ports 53
  environment: 
    ETCD_AUTHORITY: 127.0.0.1:{{ etcd_client_port }}
  when: result|failed

- name: add webrouter rules allow to tcp 80 and 443
  command: calicoctl profile webrouter rule add inbound --at=1 allow tcp to ports {{ item }}
  with_items:
    - "80"
    - "443"
  environment: 
    ETCD_AUTHORITY: 127.0.0.1:{{ etcd_client_port }}
  when: result|failed

- name: add lain tag to webrouter profile
  command: calicoctl profile webrouter tag add lain
  environment: 
    ETCD_AUTHORITY: 127.0.0.1:{{ etcd_client_port }}
  when: result|failed

- name: add default calico rules to etcd
  command: >
          etcdctl set /lain/config/calico_default_rule
          "{\"outbound\":
          [\"deny tcp to ports 2375 cidr {{ node_network }} --at=1\",
          \"deny tcp to ports 2376 cidr {{ node_network }} --at=1\",
          \"deny tcp to ports 4001 cidr {{ node_network }} --at=1\",
          \"deny tcp to ports 7001 cidr {{ node_network }} --at=1\",
          \"deny tcp to ports 9002 cidr {{ node_network }} --at=1\",
          \"deny tcp to ports 9003 cidr {{ node_network }} --at=1\"],
          \"inbound\": []}"
  when: is_lain_manager
